# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* loaded in the `_config.yml` file.
# Instead, it is loaded *AFTER* the `_config.yml` file.
# This means that if you use 'theme: just-the-docs' in your `_config.yml`,
# you can use this file to override certain settings.

title: Netty-SocketIO
description: Socket.IO server implementation for Java based on Netty framework
url: https://socketio4j.github.io
baseurl: /netty-socketio

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.svg"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Netty-SocketIO on GitHub":
    - "https://github.com/socketio4j/netty-socketio"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Google Analytics Tracking (optional)
# Supports a Google Analytics tracking ID
# ga_tracking: UA-1234567-89
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings

# Exclude from processing
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gem/
  - vendor/ruby/

# Set the theme
theme: just-the-docs

# Set the search tokenizer
search_tokenizer_separator: /[\s/]+/

# Enable or disable the copy button on code
copy_button: true

# Enable or disable copy button for shell commands
copy_button_prompt: "$ "

# Footer content
# appears at the bottom of every page's main content
footer_content: "Licensed under the <a href=\"https://github.com/socketio4j/netty-socketio/blob/main/LICENSE.txt\">Apache License 2.0</a>."

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e, %Y at %I:%M %p"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/socketio4j/netty-socketio"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
gh_edit_source: "docs"

# Callouts styling
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green

# Javadoc paths
javadoc:
  core: "/javadoc/core"
  spring: "/javadoc/spring"
  spring_boot_starter: "/javadoc/spring-boot-starter"
  quarkus: "/javadoc/quarkus"
  micronaut: "/javadoc/micronaut"

