version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:latest
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    command: jekyll serve --host 0.0.0.0 --force_polling
    environment:
      - JEKYLL_ENV=development

